name: GuildShelter
main: org.windy.guildshelter.plugin
version: ${mod_version}
api-version: 1.21
depend:
  - Residence
commands:
  gs:
    description: GuildShelter插件命令
    usage: /gs <debug|spawn|setspawn>
    subcommands:
      debug:
        description: 调试命令
        usage: /gs debug <genplat>
      spawn:
        description: 设置或传送到公会出生点
        usage: /gs spawn
      setspawn:
        description: 设置公会出生点
        usage: /gs setspawn