{
  "formatVersion": "1.1",
  "component": {
    "group": "org.windy",
    "module": "GuildShelter",
    "version": "1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "GuildShelter-1.3-SNAPSHOT.jar",
          "url": "GuildShelter-1.3-SNAPSHOT.jar",
          "size": 55734,
          "sha512": "f55fbc7efb4756244d2ede659e26a0a78303dbd7ae1cfbacf0c251368a79088076c93add3e26f0f2c738ee715d839c6d47f65f78858009a3412d9d704e528221",
          "sha256": "9312bf9eeab7e80ef2bace4c5145c6b5f993fc5574af3b0c0fc8d3904a486f7e",
          "sha1": "1b9945f4d6acc6f5f5064ba7ebb07edf6c5f3946",
          "md5": "16e37315ff7deb0d47ab6a97a76cf423"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "5.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "GuildShelter-1.3-SNAPSHOT.jar",
          "url": "GuildShelter-1.3-SNAPSHOT.jar",
          "size": 55734,
          "sha512": "f55fbc7efb4756244d2ede659e26a0a78303dbd7ae1cfbacf0c251368a79088076c93add3e26f0f2c738ee715d839c6d47f65f78858009a3412d9d704e528221",
          "sha256": "9312bf9eeab7e80ef2bace4c5145c6b5f993fc5574af3b0c0fc8d3904a486f7e",
          "sha1": "1b9945f4d6acc6f5f5064ba7ebb07edf6c5f3946",
          "md5": "16e37315ff7deb0d47ab6a97a76cf423"
        }
      ]
    }
  ]
}
